"""Tool for reading and summarizing CFG JSON files for LLM consumption."""

import json
from pathlib import Path
from typing import Dict, Any, List, Optional

from langchain.tools import BaseTool
from pydantic import BaseModel, Field


class CFGReaderInput(BaseModel):
    """Input schema for CFG reader tool."""

    cfg_json_path: str = Field(
        ..., description="Path to cfg.json file generated by cfg_generator"
    )
    max_nodes: int = Field(
        default=100,
        description="Maximum number of nodes to include in summary (default: 100)"
    )
    include_paths: bool = Field(
        default=False,
        description="Whether to include execution paths (default: False, saves tokens)"
    )
    focus_on_security: bool = Field(
        default=True,
        description="Prioritize security-relevant nodes (default: True)"
    )


class CFGReaderTool(BaseTool):
    """
    Reads and summarizes CFG JSON files for LLM analysis.
    
    This tool reads CFG JSON files generated by cfg_generator and creates
    a compact, token-efficient summary that can be directly used by the LLM.
    """

    name: str = "cfg_reader"
    description: str = (
        "Read and summarize Control Flow Graph (CFG) JSON files for analysis. "
        "Takes a cfg.json file path (returned by cfg_generator) and returns a compact summary "
        "focusing on security-relevant control flow patterns, branches, loops, and function calls. "
        "Use this after cfg_generator to get CFG information in a token-efficient format. "
        "The summary includes key nodes, execution paths, and vulnerability-relevant sections."
    )
    args_schema: type[BaseModel] = CFGReaderInput

    def _run(
        self,
        cfg_json_path: str,
        max_nodes: int = 100,
        include_paths: bool = False,
        focus_on_security: bool = True,
    ) -> str:
        """Read and summarize CFG JSON file."""
        cfg_path = Path(cfg_json_path)
        
        if not cfg_path.exists():
            return json.dumps({
                "error": f"CFG file not found: {cfg_json_path}",
                "summary": None
            })

        try:
            with open(cfg_path, "r", encoding="utf-8") as f:
                cfg_data = json.load(f)

            summary = self._create_summary(
                cfg_data,
                max_nodes=max_nodes,
                include_paths=include_paths,
                focus_on_security=focus_on_security,
            )

            return json.dumps(summary, indent=2)

        except Exception as e:
            return json.dumps({
                "error": f"Failed to read CFG: {str(e)}",
                "summary": None
            })

    def _create_summary(
        self,
        cfg_data: Dict[str, Any],
        max_nodes: int = 100,
        include_paths: bool = False,
        focus_on_security: bool = True,
    ) -> Dict[str, Any]:
        """Create a compact summary of CFG data."""
        summary = {
            "total_files": len(cfg_data.get("files", [])),
            "total_functions": 0,
            "key_functions": [],
            "security_relevant_nodes": [],
            "estimated_tokens": 0,
        }

        all_functions = []

        # Process each file
        for file_info in cfg_data.get("files", []):
            file_path = file_info.get("file", "unknown")
            functions = file_info.get("functions", [])

            for func in functions:
                func_name = func.get("name", "anonymous")
                func_id = func.get("id", "")
                nodes = func.get("nodes", [])
                
                summary["total_functions"] += 1

                # Collect security-relevant nodes
                security_nodes = []
                important_nodes = []

                for node in nodes:
                    node_id = node.get("id", "")
                    node_kind = node.get("kind", "")
                    node_meta = node.get("meta", {})

                    # Identify security-relevant nodes
                    if focus_on_security and self._is_security_relevant(node_kind, node_meta):
                        security_nodes.append({
                            "id": node_id,
                            "kind": node_kind,
                            "meta": self._extract_key_meta(node_meta),
                        })

                    # Collect important control flow nodes
                    if node_kind in {"Branch", "Loop", "CallExpression", "Return", "Throw"}:
                        important_nodes.append({
                            "id": node_id,
                            "kind": node_kind,
                            "meta": self._extract_key_meta(node_meta),
                        })

                # Limit nodes per function
                func_security_nodes = security_nodes[:max_nodes // 4]
                func_important_nodes = important_nodes[:max_nodes // 4]

                all_functions.append({
                    "file": file_path,
                    "name": func_name,
                    "id": func_id,
                    "node_count": len(nodes),
                    "security_nodes": func_security_nodes,
                    "important_nodes": func_important_nodes,
                })

        # Select top functions (prioritize those with security nodes)
        functions_with_security = [f for f in all_functions if f["security_nodes"]]
        other_functions = [f for f in all_functions if not f["security_nodes"]]

        summary["key_functions"] = (
            functions_with_security[:max_nodes // 2] +
            other_functions[:max_nodes // 2]
        )[:max_nodes]

        # Flatten security nodes
        for func in summary["key_functions"]:
            summary["security_relevant_nodes"].extend(func["security_nodes"])

        summary["security_relevant_nodes"] = summary["security_relevant_nodes"][:max_nodes]

        # Estimate tokens
        total_chars = len(json.dumps(summary))
        summary["estimated_tokens"] = total_chars // 4

        return summary

    def _is_security_relevant(self, kind: str, meta: Dict[str, Any]) -> bool:
        """Check if a node is security-relevant."""
        # Security-relevant node types
        security_kinds = {
            "CallExpression",  # Function calls
            "AssignmentExpression",  # Variable assignments
            "BinaryExpression",  # Operations
            "MemberExpression",  # Property access
        }

        if kind in security_kinds:
            # Check for dangerous function calls
            callee = meta.get("callee", "")
            if callee:
                dangerous = {
                    "eval", "exec", "Function", "setTimeout", "setInterval",
                    "innerHTML", "dangerouslySetInnerHTML", "document.write",
                    "query", "queryRaw", "execute", "exec", "spawn", "execFile",
                }
                if any(df in str(callee).lower() for df in dangerous):
                    return True
            return True

        return False

    def _extract_key_meta(self, meta: Dict[str, Any]) -> Dict[str, Any]:
        """Extract only key metadata to reduce token usage."""
        key_meta = {}
        
        if "callee" in meta:
            key_meta["callee"] = meta["callee"]
        if "arguments" in meta:
            # Limit arguments
            key_meta["arguments"] = meta["arguments"][:3]
        if "property" in meta:
            key_meta["property"] = meta["property"]
        
        return key_meta

    async def _arun(self, *args, **kwargs):
        raise NotImplementedError("Async not supported yet.")


__all__ = ["CFGReaderTool"]

